---
- name: Patch a new F5 VE OVA with F5 vApp custom Properties and Migrate it as a vCenter Template
  hosts: me
  connection:local
  gather_facts: false

  pre_tasks:
  - name: 1.Create a temporary directory
    tempfile:
      state: directory
      suffix: "_tempdir"
    register: tmp

  roles:
    - role: fch.uploadOVA
      vars:
          F5_OVA: "BIGIP-15.1.0.1-0.0.4.ALL-vmware.ova"
          IMAGE_PATH: "/var/images/"
          tempDir: "{{ tmp.path }}"
